global:
  scrape_interval: 10s

scrape_configs:
- job_name: nginx-exporter
  static_configs:
  - targets:
    - nginx-exporter:9113

- job_name: prometheus
  static_configs:
  - targets:
    - prometheus:9090

- job_name: node
  static_configs:
  - targets:
    - node-exporter:9100

- job_name: cgroup
  static_configs:
  - targets:
    - cgroup-exporter:9101
